DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS order_content CASCADE;
DROP TABLE IF EXISTS ingredient CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
DROP TABLE IF EXISTS recipe CASCADE;
DROP TABLE IF EXISTS z_report CASCADE;
DROP TABLE IF EXISTS nutrition_info CASCADE;
DROP TABLE IF EXISTS allergens CASCADE;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS verificationToken CASCADE;
DROP TYPE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS authenticator CASCADE;

DROP TYPE IF EXISTS role;
DROP TYPE IF EXISTS paymethod;